version: '3.9'

services:
  markdown-flow-db:
    build: ./db/
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - markdown-flow-db:/var/lib/mysql
  app:
    depends_on:
      - markdown-flow-db
    build: ./apiServer/
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=markdown-flow-db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT

volumes: 
  markdown-flow-db: