# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mf-db
  labels:
    app: mf-db
    app.kubernetes.io/name: mf-db
spec:
  publishNotReadyAddresses: true
  ports:
  - name: mf-db
    port: 3306
  clusterIP: None
  selector:
    app: mf-db
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mf-db-read
  labels:
    app: mf-db
    app.kubernetes.io/name: mf-db
    readonly: "true"
spec:
  ports:
  - name: mf-db
    port: 3306
  selector:
    app: mf-db